AllCops:
  TargetRubyVersion: 2.3
  Include:
    - Gemfile
    - Rakefile
    - config.ru
  Exclude:
    - bin/*
    - db/**/*
    - node_modules/**/*
    - spec/*_helper.rb
Metrics/LineLength:
  Max: 120
Documentation:
  Enabled: false
